name: scanner_for_android
description: "تطبيق إسقاط الدرجات بالأكواد والتعرف الذكي على النصوص"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  # مكتبة اختيار وقراءة ملفات الإكسيل
  file_picker: ^8.0.0
  excel: ^4.0.6

  # مكتبة تشغيل الكاميرا وقراءة الكيور آر كود
  mobile_scanner: ^5.1.1

  # مكتبة معالجة الصور وقراءة الدرجات بخط اليد
  google_mlkit_text_recognition: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
